# Generated by Django 3.2.4 on 2021-06-21 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('chave_google', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('nivel', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('complete', models.BooleanField(default=False)),
                ('data_create', models.DateField(auto_now_add=True)),
                ('data_conclusao', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefas.usuario')),
            ],
        ),
    ]
