# Generated by Django 3.2.4 on 2021-06-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data_concluded',
            field=models.DateField(blank=True, null=True),
        ),
    ]
